### ISSUE TITLE
Comentarios QMP2

### ISSUE THREAD

**Issue by gastonprieto** [radevaom/QMP2#1]
* Bien planteada la idea de borrador :)

* Ojo que estas haciendo cosas que no piden 

  * [public void guardarBorradorUltimaPrenda() {](https://github.com/radevaom/QMP2/blob/84448fa203c711dda7796e396a4ec65f8561df63/src/main/java/prendas/Atuendo.java#L18)

  * [if (prendas.stream().noneMatch(prenda1 -> prenda1.tipoDePrenda.getCategoria() == prenda.tipoDePrenda.getCategoria())) {](https://github.com/radevaom/QMP2/blob/84448fa203c711dda7796e396a4ec65f8561df63/src/main/java/prendas/Atuendo.java#L11-L12) Ojo que esto no lo pedía, por ejemplo no podría tener un atuendo que tenga  mas de un accesorio.

* [prenda1.tipoDePrenda.getCategoria() == Categoria.ACCESORIOS](https://github.com/radevaom/QMP2/blob/84448fa203c711dda7796e396a4ec65f8561df63/src/main/java/prendas/Atuendo.java#L24) para comparar en general tratar de usar `.equals(..)` en vez de == ya quee son distintos, uno es igualdad(equivalencia) en vez de identidad.

* [public void guardarBorradorUltimaPrenda() {](https://github.com/radevaom/QMP2/blob/84448fa203c711dda7796e396a4ec65f8561df63/src/main/java/prendas/Atuendo.java#L18-L19)

Esto no es algo que corresponda al atuendo, podrías estar creando una prenda sin que este ligada a un atuendo.

* [](https://github.com/radevaom/QMP2/blob/84448fa203c711dda7796e396a4ec65f8561df63/src/main/java/aplicacion/Administrador.java#L4-L8)

Esta clase no esta aportando comportamiento.

**Comment by radevaom** [comment]
Buenas Gastón, gracias por corregir!

> Ojo que estas haciendo cosas que no piden
 `  public void guardarBorradorUltimaPrenda() {`

si, eso me quedo colgado porque al principio no entendí bien la idea del borrador.

 ```
   if (prendas.stream().noneMatch(prenda1 -> prenda1.tipoDePrenda.getCategoria() == prenda.tipoDePrenda.getCategoria())) {
      this.prendas.add(prenda);
```

Eso lo puse para que a un atuendo no se puedan mas de 1 misma categoria (para no tener 5 zapatos, 2 camperas, etc): pregunto si en mi lista de prendas no existe ninguna con la categoria que quiero agregar y si no existe agrego la prenda.


y voy a empezar a usar el .equals() 

Muchas gracias Gastón!!
